# render.yaml

services:
  - type: web
    name: tinytography-sales-channel
    env: node
    plan: starter
    region: oregon
    branch: main
    repo: https://github.com/lotodee/tinytography-sales-channel.git
    buildCommand: |
      npm install
      npm run setup
      npm run build
    startCommand: npm run start
