# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d70ac85786c63a5c1512f1f185c642c1"
name = "Tinytography Sales Channel"
handle = "tinytography-sales-channel"
application_url = "https://tintography-sales-channel.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[auth]
scopes = "read_products, read_orders, write_orders, read_inventory, write_products, write_inventory, write_fulfillments, read_fulfillments"
redirect_urls = [

  https://tintography-sales-channel.onrender.com/auth/shopify/callback
  https://tintography-sales-channel.onrender.com/api/auth/callback
  https://tintography-sales-channel.onrender.com/auth/callback
  https://tintography-sales-channel.onrender.com/custom/auth
  https://tintography-sales-channel.onrender.com/custom/auth/callback

]

[pos]
embedded = false

